<?php
    $models = Mage::getModel('pro/pro')->getCollection();
    $edit = Mage::getModel('pro/pro')->load($_GET['id']);
?>

<form  method="post" name="item_form"  id="item_form" action="<?php echo $this->getBaseUrl().'pro/index/edit' ?>">
    <input type="hidden" name="id" value="<?php echo $edit->getstd_id(); ?>" />
    <label for="title"><?php echo $this->__('Stdname:- ') ?><span class="required">*</span></label>
    <input type="text" id="name" name="name" value="<?php echo $edit->getStdname(); ?>" class="input-text required-entry" />
    <br>
    <br>
    <label for="title"><?php echo $this->__('Email Id:- ') ?><span class="required">*</span></label>
    <input type="text" id="Email" name="Email" value="<?php echo $edit->getEmail(); ?>" class="input-text required-entry" />
    <br>
    <br>    
    <label for="title"><?php echo $this->__('Rollno:- ') ?><span class="required">*</span></label>
    <input type="text" id="Roll" name="Roll" value="<?php echo $edit->getRollno(); ?>" class="input-text required-entry" />
    <br>
    <br>
    gender:
    <input type="radio" name="gender" value="male" <?php echo ("male" == $edit->getGender()) ? 'checked' : ''; ?>> Male
    <input type="radio" name="gender" value="female" <?php echo ("male" != $edit->getGender()) ? 'checked' : ''; ?>> Female
    <br>
    <br>
    status:
    <select name="status">              
        <option value='1' <?php echo (1 == $edit->getStatus()) ? 'selected' : ''; ?>>Active</option>
        <option value='2' <?php echo (2 == $edit->getStatus()) ? 'selected' : ''; ?>>Inactive</option>
    </select>
    <br>
    <br>
    <button type="submit" title="Update" name="submit" >Update</button>
</form>
