<form method="POST" action="<?php echo $this->getUrl('pro/index/save'); ?>" enctype="multipart/form-data">
    <fieldset>
        <legend>Student Information:</legend>
        Name:<br>
        <input type="text" name="name" minlength="3" placeholder="Enter Name" required>
        <br>
        Email:<br>
        <input type="email" name="email" placeholder="Enter Email" required>
        <br>
        Roll No.:<br>
        <input type="number" name="rollno" min="1" placeholder="Enter Roll No." required>
        <br>
        gender:<br>
        <input type="radio" name="gender" value="male" checked> Male
        <input type="radio" name="gender" value="female"> Female
        <br>
        status:<br>
        <select name="status">
            <option value="1">Active</option>
            <option value="2">Inactive</option>
        </select>
        <br>    
        <br>
        <input type="submit" value="Submit">
    </fieldset>
</form>


<br>    
<br>

<?php $collection = Mage::getModel('pro/pro')->getCollection()->setOrder('rollno', 'DESC'); ?>

<div id="table_id">
    <table width="100%" border="1px" style="text-align:center">
    <thead>
        <th><?php echo $this->__('Id'); ?></th>
        <th><?php echo $this->__('Name'); ?></th>
        <th><?php echo $this->__('Email'); ?></th>
        <th><?php echo $this->__('Roll No.'); ?></th>
        <th><?php echo $this->__('Gender'); ?></th>
        <th colspan="2"><?php echo $this->__('Action'); ?></th>
    </thead>
    <?php foreach($collection as $collect):?>
        <tr>
            <td>
                <?php echo $collect->getstd_id(); ?>
            </td>   
            <td>
                <?php echo $collect->getStdname(); ?>
            </td>
            <td>
                <?php echo $collect->getEmail(); ?>
            </td>
            <td>
                <?php echo $collect->getRollno(); ?>
            </td>
            <td>
                <?php echo $collect->getGender(); ?>
            </td>
            <td>
                <a href="<?php echo $this->getBaseUrl().'pro/index/editData?id='.$collect->getstd_id() ?>">
                    <?php echo $this->__('EDIT'); ?></a>
            </td>
            <td>
                <a href="<?php echo $this->getBaseUrl().'pro/index/deletedata?id='.$collect->getstd_id() ?>">
                    <?php echo $this->__('DELETE'); ?></a>
            </td>
        </tr>
    <?php endforeach;?>
    </table>
</div>
